### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by cmadland** [OleVik/grav-theme-scholar#1]
Hi @OleVik !
This looks like an interesting project! I'm using Paul Hibbitts' Open Publishing theme to host my site where I am planning to host my dissertation. [grav.madland.ca](https://grav.madland.ca).

I'd be happy to talk about scholarly publishing using Grav if you're interested.

Colin

**Comment by OleVik** [comment]
Hey Colin,

My hope is that Scholar will be usable for both presenting research projects broadly, but in time also be usable for writing research. I'm starting with the Documentation-like parts of it, because it fits neatly in with Paul's Open Publishing Theme and associated Themes and Skeletons.

I'd be very interested to hear your thoughts on using Grav for hosting your dissertation, both possibilities and limitations. GitHub issues are a bit restricting in this regard though - they are a bit much to keep track of with many going at once - so hit me up on Discord anytime!

Best regards, Ole

**Comment by OleVik** [comment]
@cmadland After some thinking I have decided to utilize the issue- and project-system for more broader discussions as well. I opened #2 in case you have time to add anything to it, would appreciate some input on how to make writing, editing, and organizing research, papers, or other content easy for the user.
