### ISSUE TITLE
Installation Difficulty (Dependency "Error" is required)

### ISSUE THREAD

**Issue by j3kennard** [OleVik/grav-theme-scholar#5]
When I run `sudo bin/gpm install scholar` I get the following feedback/error, and Scholar is unable to be installed:

```
GPM Releases Configuration: Stable

Dependency Error is required in version 1.6.21 which is higher than the latest release, 1.6.2. Try running `bin/gpm -f index` to force a refresh of the GPM cache
```

I assume the fix is relatively simple, but I just don't know what it is. Do I need to downgrade Grav to 1.6.2 to match the version of Error?

**Comment by OleVik** [comment]
This is an inherent error in the current version of Grav's Package Manager I think; it does not resolve versions correctly when bound to a constraint. But you can download [Grav 1.6.21 directly](https://github.com/getgrav/grav/releases/tag/1.6.21), or [packaged with plugins and Admin](https://getgrav.org/download/core/grav-admin/1.6.21).

**Comment by j3kennard** [comment]
Thanks so much for the timely reply! So is this error saying that my Grav installation is not up to date? Or does it mean that the "Error" dependency isn't?

**Comment by OleVik** [comment]
It is saying that the dependencies set in the Error-plugin are higher than in Scholar, so it won't install it. This is a problem of constraint-resolution in the ecosystem of Grav packages, where Scholar is currently locked to require Grav 1.6.21, because of instabilities in the beta- and testing-releases of Grav, and needing the Static Generator plugin. This constraint will be loosened up when Grav 1.7.0 is releases, but until then you should be able to get by with installing it with a package that contains Grav 1.6.21 + Admin, as linked above.

You can also install [v1.0.7 of the Scholar-skeleton](https://github.com/OleVik/grav-skeleton-scholar/releases/tag/1.0.7), which contains Grav 1.6.21 + Admin + Scholar + sample content + recommended extensions.

**Comment by j3kennard** [comment]
Okay great, I’ll give your suggestions a shot. Thank you!

**Comment by Nithilher** [comment]
Installed the skeleton. If offers un update of the scholar theme to 2.0.0, bu when I try to install it, I get the above mentioned error "Dependency Error is required in version 1.6.21 which is higher than the latest release, 1.6.2. Try running `bin/gpm -f index` to force a refresh of the GPM cache". Is it currently not possible to update to the newest version of your theme?

**Comment by OleVik** [comment]
This is essentially the same error as above, which stems from version-resolution. As long as you are on the 1.6 minor-version of Grav itself, updating Scholar and other dependencies should be safe. You may have to do this manually though, as the [current restraint](https://github.com/OleVik/grav-theme-scholar/blob/master/blueprints.yaml#L15) is set to prevent accidental upgrades using Scholar with Grav 2.0.
