### ISSUE TITLE
Scholar skeleton + upgrade = server error

### ISSUE THREAD

**Issue by hellquist** [OleVik/grav-theme-scholar#8]
After having tried all kinds of ways of installing Scholar I opted for the skeleton route. It comes with the current release of Grav, whereas Scholar documentation says it has been made and tested with the latest 1.7rc of Grav.

Installing the skeleton, and then going to plugins, enabling "testing" (as opposed to "stable") allows me to upgrade Grav from 1.6.23 to 1.7rc8. That will however crash the entire site, showing a "server error" page that complains about something with autoload. Sorry, taking this from memory from earlier today so can't be more precise right now. I did repeat it 3 times though.

When looking at the file it was pointing to I noticed that it gave reference to https://github.com/OleVik/grav-plugin-scholar/ on two place. Do note "plugin", not "theme" or "skeleton" in that URL. I figured I perhaps had missed to install a plugin after all, but going to that URL leads to a 404 here on Github. I have no idea if that is related to anything or not, but I did notice it.

**Comment by OleVik** [comment]
It has been, but midway through the release candidates for 1.7 of Grav, the API changed. This broke significant parts of the theme, as well as many plugins. Until 1.7 is stable, Scholar is unlikely to support it out of the box. I don't entirely know where that incorrect URL emanates from, but it's a typo somewhere.

Because of the way Grav is developed, all central extensions - Admin, Problems, Error, Form, Quark - align tightly with Core. So nothing is ever stable unless those extensions are aligned with Grav itself. Therefore Scholar is ["locked"](https://github.com/OleVik/grav-theme-scholar/issues/5#issuecomment-599197366) to the stable version, which implicitly should constrain all extensions to stable as well.

The issue regarding GPM's version-resolution and -recognition has been discussed on Grav's own repository, and has an open issue there (2827).
